### ISSUE TITLE
Config is missing support for setting ignore pattern

### ISSUE THREAD

**Issue by dmatora** [mrdavidlaing/vagrant-unison#15]

**Comment by trompx** [comment]
Hello dmatora, thank you for adding all those new functionalities!

Unfortunatly, despite all your patches, I can not get this to work.
For this new setting, if I add in Vagrantfile "config.sync.ignore = "Name {.idea,.DS_Store}"", when I "vagrant sync", I get the following error :

path_to_plugin/lib/vagrant-unison/command.rb:90:in `[]=': wrong number of arguments (1 for 2) (ArgumentErro
r)
path_to_plugin/lib/vagrant-unison/command.rb:90:in`trigger_unison_sync'
path_to_plugin/lib/vagrant-unison/command.rb:15:in `block in execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/plugin/v2/command.rb:226:in`block in with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/plugin/v2/command.rb:220:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/plugin/v2/command.rb:220:in`with_target_vms'
path_to_plugin/lib/vagrant-unison/command.rb:12:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/cli.rb:42:in`execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/environment.rb:301:in `cli'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/bin/vagrant:174:in`<main>'

Any idea?

I can get past this error by removing the ignore setting in Vagrantfile but then I get the following error :

Full command causing error:
["unison", "-batch", "-sshargs", "-p 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i C:/Websites/websites/.vagrant/machines/machine_name
/virtualbox/private_key", "C:/Websites/websites/", "ssh://vagrant@127.0.0.1//vagrant"]

Replacing ssh_info[:private_key_path].map { |p| "-i '#{p}'" },
By ssh_info[:private_key_path].map { |p| "-i #{p}" },
did not work.

Windows 8.1 - Vagrant 1.7.1

Would love to have all those patches merged so installing via "vagrant plugin install vagrant-unison" reflects all the changes.

Thank you again.

**Comment by dmatora** [comment]
What about vagrant sync-repeat?
does it work?

**Comment by andrewmriley** [comment]
I ran into this issue as well. sync-repeat does work but sync does not.
